### ISSUE TITLE
why the number of kernels equals to attention kernels 

### ISSUE THREAD

**Issue by talorwu** [danielegrattarola/keras-gat#1]
I don not think the number of kernels( as K1) must equals to the number of attention kernel(as K2). It is to say K1 <> K2

**Comment by danielegrattarola** [comment]
If you look at Equations 5 and 6 in the paper you will see that both W and α_ij depend on k. 
Also from the paper: 

> α_ij are normalized attention coefficients computed by the k-th attention mechanism (a ), and W is the corresponding input linear transformation’s weight matrix

**Comment by talorwu** [comment]
Awesome！you are right ,thx
