### ISSUE TITLE
PPI

### ISSUE THREAD

**Issue by xuhaiyun43** [danielegrattarola/keras-gat#18]
Hi, thanks for sharing the code, could you please provide codes for training ppi data? I see it has a significant improvement over other methods on this dataset.
Codes for ppi would be really great, I second that. Thanks a lot for sharing the code, anyway

**Comment by danielegrattarola** [comment]
Hi, 
the code implementing the GAT layer should be the same, but I don't really have any plans to add a dedicated example script for the PPI dataset. 
The official repo by Veličković has some utils that can be used for PPI, so maybe try looking at that. 

Cheers,
Daniele
