### ISSUE TITLE
Visualization Qesition

### ISSUE THREAD

**Issue by tanjia123456** [danielegrattarola/keras-gat#29]
hello, I would like to ask, what method did you use to visualize the result in the end? 
Do you mind sharing the source code of the visualization? thank you a lot

Looking forward to your reply

**Comment by danielegrattarola** [comment]
Hi, I think you should ask the question on [the official repo](https://github.com/PetarV-/GAT) of the paper. This is not an official implementation and I am not affiliated with the authors. 

Cheers

**Comment by tanjia123456** [comment]
ok, any way, thank you for your reply
