### ISSUE TITLE
Input shape

### ISSUE THREAD

**Issue by Kareshi-X** [danielegrattarola/keras-gat#35]
Thanks for your work!
I found the input shape of your GAT is (nodes, features), in my network the input shape is (batch_size, nodes, features). So I run your code but it doesn't work any more. Please help me ,thanks a lot!😭

**Comment by danielegrattarola** [comment]
This repo is out of date, you should check out [the GATConv implementation in Spektral](https://graphneural.network/layers/convolution/#gatconv).

**Comment by Kareshi-X** [comment]
thanks!!😘
