### ISSUE TITLE
What is behavior of K.dot?

### ISSUE THREAD

**Issue by sharpstill** [danielegrattarola/keras-gat#5]
in line:
https://github.com/danielegrattarola/keras-gat/blob/master/keras_gat/graph_attention_layer.py#L100
the shape of `combination_slices` is (N,N,2F') and the shape of `attention_kernel` is (2F', 1) .
So traditional matrix multiplication can't multiply that. What is the result of this line?

**Comment by danielegrattarola** [comment]
>  traditional matrix multiplication can't multiply that

Why not? N x N x 2F' x 2F' x 1 = N x N x 1.
The `squeeze` then removes that 1-dimension and leaves you with N x N.
I spotted a typo in the comments: 
```py
dense = K.squeeze(K.dot(combination_slices, attention_kernel), -1) # a(Wh_i, Wh_j) in the paper (N x N x 1)
```
is supposed to be 
```py
dense = K.squeeze(K.dot(combination_slices, attention_kernel), -1) # a(Wh_i, Wh_j) in the paper (N x N)
```

Cheers

**Comment by sharpstill** [comment]
@danielegrattarola I am sorry I didn't express my question clearly. My concern is that I am using `chainer ` framework to re-implement part of your code, because `chainer`  supply a traditional fully connected(FC) layer, Can I re-implement this  `attention_kernel` using a FC layer?? Because your `combination_slices shape = (N,N,2F')`, so I **reshape** `combination_slices ` to `(N^2, 2F)`, where `N^2` became batch dimension.

Then a **traditional fc layer** will convert 2F' to 1 dimension, along mini-batch of `N^2`. Does this way correct of re-produce your function?

**Comment by sharpstill** [comment]
I mean do fc layer calculate the correct result answer of exactly what you do?

**Comment by danielegrattarola** [comment]
If I understood you correctly, then yes.  
The `attention_kernel` is just a matrix of shape `(2F', 1)`, if you used a FC layer that took `2F'`-dimensional inputs and returned scalars, then you layer would internally store a matrix of the same size and multiply it by the input. 
Hope this helps.

**Comment by sharpstill** [comment]
Because `attention_kernel ` is just size of `(2F', 1)`, Imaging there is big graph where exists a lot of nodes. The attention FC layer just has `(2F', 1)` weight parameters,  can it have **enough** capability to deal with so big graph?  Does original paper's code did exactly what you do in this attention part?

**Comment by danielegrattarola** [comment]
I haven't checked the original code in depth, but that's how it's done in the paper and that's the only logical way to do it. Matrix algebra doesn't leave you with many slack to change things up.

To anser your question, yes, `2F'` weights are enough to generalize :)
