### ISSUE TITLE
Result of example script with 8 attention heads

### ISSUE THREAD

**Issue by matthias-samwald** [danielegrattarola/keras-gat#6]
Just a quick information: I ran the example script on a GTX1080 after changing to 8 attention heads instead of 3, test accurracy is .8170 

How are you developing such cutting-edge stuff without a proper GPU? :)

**Comment by danielegrattarola** [comment]
Wonderful, thank you so much! I updated the README with the result and a link to your profile.

>How are you developing such cutting-edge stuff without a proper GPU? :)

Pain and a lot of approximate results, my friend :) (I actually asked my advisor for a proper workstation, it should be coming in the next weeks with 2 (T-W-O) Titan Vs  💯 💯 )
